In [86]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [87]:
dataset = pd.read_csv('Data.csv')

In [88]:
dataset.head()

ack  ack_A  ack_B  bytes  ...  ttl_sum  ttl_thirdQ      ttl_var  device_category
0    9      5      5   1213  ...     7140        64.0    91.248560  security_camera
1    9      5      5   1213  ...     4185       235.0  6290.100000  security_camera
2    9      5      5   1213  ...     7140       235.0  6290.100000  security_camera
3    9      5      5   1213  ...     1336        64.0   125.840000  security_camera
4    9      5      5   1213  ...     1210        64.0   122.571429  security_camera

[5 rows x 114 columns]

In [89]:
dataset.columns

Index(['ack', 'ack_A', 'ack_B', 'bytes', 'bytes_A', 'bytes_A_B_ratio',
       'bytes_B', 'ds_field_B', 'duration', 'http_dom_host_alexaRank',
       ...
       'ttl_entropy', 'ttl_firstQ', 'ttl_max', 'ttl_median', 'ttl_min',
       'ttl_stdev', 'ttl_sum', 'ttl_thirdQ', 'ttl_var', 'device_category'],
      dtype='object', length=114)

In [90]:
dataset['device_category'].nunique()

10

In [91]:
X =  dataset.iloc[:, :-1]
y = dataset.iloc[:, -1] # the first : is for the rows

In [92]:
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [93]:
print("Are there missing data? :", dataset.isnull().any().any())

Are there missing data? : False


In [94]:
discrete_features=[]
for col in dataset.columns[:-1]: # excluding the last columns
  if np.array_equal(dataset[col].values, dataset[col].values.astype(int)):
    discrete_features.append(col)

print(f'Total discrete features {len(discrete_features)} : ')
print(discrete_features)

Total discrete features 36 : 
['ack', 'ack_A', 'ack_B', 'bytes', 'bytes_A', 'bytes_B', 'ds_field_B', 'http_dom_host_alexaRank', 'packet_size_A_max', 'packet_size_A_sum', 'packet_size_B_max', 'packet_size_B_min', 'packet_size_B_sum', 'packet_size_max', 'packet_size_min', 'packet_size_sum', 'packets', 'packets_A', 'packets_B', 'ssl_dom_server_name_alexaRank', 'ttl_A_avg', 'ttl_A_entropy', 'ttl_A_firstQ', 'ttl_A_max', 'ttl_A_median', 'ttl_A_min', 'ttl_A_stdev', 'ttl_A_sum', 'ttl_A_thirdQ', 'ttl_A_var', 'ttl_B_max', 'ttl_B_min', 'ttl_B_sum', 'ttl_max', 'ttl_min', 'ttl_sum']


In [95]:
X = X.values
y = y.values

In [96]:
#Onehotencoding (getdummies)
y_label = pd.get_dummies(y[::-1]).values

In [97]:
y_label.shape

(1900, 10)

In [98]:
#feature selection
#from sklearn.feature_selection import SelectKBest, f_classif
#from sklearn.feature_selection import SelectKBest
#from sklearn.feature_selection import mutual_info_classif

#def select_features(X_train, y_train, X_test):
 # selector = SelectKBest(score_func= f_classif, k= 'all')
  #selector.fit(X_train, y_train)
  #X_train_selector = selector.transform(X_train)
  #X_test_selector = selector.transform(X_test)
  #return X_train_selector, X_test_selector, selector

#

In [99]:
#X_train_selector, X_test_selector, selector = select_features(X_train, y_train, X_test)

In [100]:
#X_train_selector = pd.DataFrame(X_train_selector)

In [101]:
#X_train =  X_train_selector.iloc[:, :-1]

#y_train = X_train_selector.iloc[:, -1] 

In [102]:
#X_test_selector = pd.DataFrame(X_test_selector)


In [103]:
#X_test =  X_test_selector.iloc[:, :-1]
#y_test = X_test_selector.iloc[:, -1] 


In [104]:
#X_train_selector

In [105]:
#X_train_selector.shape

In [106]:
#X.shape

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [108]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [109]:
print(X_train)

[[-0.07378608 -0.07038395 -0.07735756 ... -0.09570581 -1.18542209
  -0.67219999]
 [-0.0657733  -0.06365491 -0.0681036  ... -0.04388545  0.59031775
   1.06100404]
 [-0.08513751 -0.08384202 -0.08661153 ... -0.10545454 -1.18542209
  -0.68230559]
 ...
 [-0.06911196 -0.06500072 -0.07339158 ... -0.0552963   0.59031775
   1.03077448]
 [-0.08847617 -0.08518783 -0.09057751 ... -0.03411314  0.90819711
   0.94110825]
 [-0.06911196 -0.06500072 -0.07339158 ... -0.0553906   0.5793564
   1.0209381 ]]


In [110]:
print(X_test)

[[-0.07578927 -0.07442137 -0.07735756 ... -0.09819309 -1.18542209
  -0.67543569]
 [-0.09448575 -0.09191686 -0.09718748 ... -0.10625613  0.90819711
  -0.68230559]
 [-0.09448575 -0.09191686 -0.09718748 ... -0.10625613  0.90819711
  -0.68230559]
 ...
 [-0.09448575 -0.09191686 -0.09718748 ... -0.0942323   0.90819711
  -0.68230559]
 [-0.08847617 -0.08518783 -0.09057751 ... -0.10105759 -1.18542209
  -0.63911746]
 [-0.08981163 -0.08787944 -0.0918995  ... -0.11009904 -0.48389524
  -0.18037525]]


In [111]:
#from sklearn import preprocessing

#le = preprocessing.LabelEncoder()
#le.fit(dataset["device_category"].unique())
#y_train_encoded = le.transform(y_train)
#x_test_encoded = le.transform(y_test)

In [112]:
X.shape

(1900, 113)

In [113]:
#from matplotlib import pyplot
#for i in range(len(selector.scores_)):
#	print('Feature %d: %f' % (i, selector.scores_[i]))

# plot the scores
#pyplot.bar([i for i in range(len(selector.scores_))], selector.scores_)
#bestsorted = selector.scores_
#pyplot.show()

In [114]:
X.shape

(1900, 113)

In [115]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [116]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['thermostat' 'watch']
 ['socket' 'water_sensor']
 ['socket' 'lights']
 ['lights' 'water_sensor']
 ['baby_monitor' 'baby_monitor']
 ['baby_monitor' 'baby_monitor']
 ['socket' 'socket']
 ['TV' 'TV']
 ['security_camera' 'security_camera']
 ['thermostat' 'thermostat']
 ['baby_monitor' 'baby_monitor']
 ['security_camera' 'security_camera']
 ['socket' 'socket']
 ['thermostat' 'thermostat']
 ['thermostat' 'thermostat']
 ['water_sensor' 'socket']
 ['socket' 'lights']
 ['lights' 'lights']
 ['security_camera' 'security_camera']
 ['TV' 'TV']
 ['baby_monitor' 'baby_monitor']
 ['TV' 'TV']
 ['socket' 'water_sensor']
 ['security_camera' 'TV']
 ['baby_monitor' 'baby_monitor']
 ['watch' 'baby_monitor']
 ['motion_sensor' 'motion_sensor']
 ['security_camera' 'security_camera']
 ['thermostat' 'thermostat']
 ['baby_monitor' 'baby_monitor']
 ['socket' 'socket']
 ['socket' 'socket']
 ['thermostat' 'thermostat']
 ['thermostat' 'thermostat']
 ['watch' 'watch']
 ['thermostat' 'thermostat']
 ['baby_monitor' 'T

In [117]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[33  4  0  1  1  0  0  0  2  0]
 [ 0 33  0  1  1  0  0  1  2  0]
 [ 0  0 28  0  0  0 11  0  0  3]
 [ 0  0  1 35  0  1  0  1  0  0]
 [ 0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  0]
 [ 0  0 16  0  0  0 18  0  0  5]
 [ 1  1  0  1  0  0  0 39  0  0]
 [ 8  3  0  0  0  0  0  2 28  0]
 [ 0  0  3  0  0  0 11  0  0  4]]


0.7868421052631579